apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-zvxo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-zvxo
    app.kubernetes.io/part-of: test-app-zafg
  name: test-component-zvxo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-zvxo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-zvxo
    spec:
      containers:
      - image: quay.io/susdas/test-images:61d12f67a48443018bbd0e5631bb0369
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
